import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import AuthProvider from "./service/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next hero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={inter.className}>
      <div>
        <Navbar></Navbar>
      </div>
       <div>
       {children}
       </div>
       <div>
        <footer className="text-center">
          This is my footer
        </footer>
       </div>
        </body>
      </AuthProvider>
    </html>
  );
}
